TRAIN:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 128
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
DATA:
  USE_OFFSET_SAMPLING: False
  DECODING_BACKEND: decord
  NUM_FRAMES: 32
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [224, 224] 
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224 #256
  INPUT_CHANNEL_NUM: [3]
  # PATH_TO_DATA_DIR: path-to-imagenet-dir
  PATH_TO_DATA_DIR: 'data_list/ucf/'
  PATH_PREFIX: ''
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  PATH_LABEL_SEPARATOR: ","
UNIFORMER:
  EMBED_DIM: [64, 128, 320, 512]
  DEPTH: [5, 8, 20, 7]
  HEAD_DIM: 64
  MLP_RATIO: 4
  DROPOUT_RATE: 0
  ATTENTION_DROPOUT_RATE: 0
  DROP_DEPTH_RATE: 0.1
  SPLIT: False
  PRETRAIN_NAME: "ucf_e2e_87.48.pyth" #checkpoint_ucf/checkpoints/ucf_e2e_87.48.pyth , checkpoint_epoch_00005_XD_80.26.pyth,uniformer_base_k600_32x4.pth
AUG:
  NUM_SAMPLE: 1
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: False
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
MULTIGRID:
  LONG_CYCLE_SAMPLING_RATE: 0
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  ZERO_WD_1D_PARAM: True
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.00005
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 30.0
  LR_POLICY: cosine
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adam
  COSINE_AFTER_WARMUP: False
MODEL:
  NUM_CLASSES: 1
  ARCH: uniformer
  MODEL_NAME: Uniformer
  LOSS_FUNC: bce_logit
  DROPOUT_RATE: 0.5
  USE_CHECKPOINT: True
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 1
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 1
DATA_LOADER:
  NUM_WORKERS: 1
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True
NUM_GPUS: 0
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
